name: calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dynamic_color: ^1.6.2
  flutter_svg: ^2.0.4
  math_expressions: ^2.3.1
  sqflite: ^2.2.6
  get: ^4.6.5
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
